#Script automatically generated by stalkess - 2021-12-09 22:34:26

#Headers
library(Momocs)
source('/Users/elizabeth/Documents/projects/functional_traits_rhf/analysis/stalkless-EGS/rhf_new_scan_just-mean/stalkless_headers.R')
cat("\n*Please* cite Momocs when using this code\nThis is little more than a minor modification of their\n*Excellent* package!\n")

#Load images
images <- list.files('/Users/elizabeth/Documents/projects/functional_traits_rhf/analysis/stalkless-EGS/rhf_new_scan_just-mean/processed_images/')
images <- images[grepl('.jpg', images, fixed=TRUE)]
images <- paste('/Users/elizabeth/Documents/projects/functional_traits_rhf/analysis/stalkless-EGS/rhf_new_scan_just-mean/processed_images/', images, sep='')
images <- import.jpg.stalkless(images)

#(Wastefully and badly) filter out the shoddy images
images <- check.images(images) #Remove those files that can't be loaded
images <- images[sapply(images, nrow) > 100] #Need at least 100 data po

#Fourier analysis
images <- Coo(images)
names(images) #You can match these names up with the statistics in the file 'statistics.txt'
fourier <- eFourier(images)
hcontrib(fourier)

#Outer edge lengths
outer.edge <- sapply(images@coo, function(x) sum(sqrt((x[-1,1]-x[-nrow(x),1])^2 + (x[-1,2]-x[-nrow(x),2])^2)))

